//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameFramework_WebRequest_WebRequestFailureEventArgsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameFramework.WebRequest.WebRequestFailureEventArgs), typeof(GameFramework.GameFrameworkEventArgs));
		L.RegFunction("Create", Create);
		L.RegFunction("Clear", Clear);
		L.RegFunction("New", _CreateGameFramework_WebRequest_WebRequestFailureEventArgs);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("SerialId", get_SerialId, null);
		L.RegVar("WebRequestUri", get_WebRequestUri, null);
		L.RegVar("ErrorMessage", get_ErrorMessage, null);
		L.RegVar("UserData", get_UserData, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameFramework_WebRequest_WebRequestFailureEventArgs(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GameFramework.WebRequest.WebRequestFailureEventArgs obj = new GameFramework.WebRequest.WebRequestFailureEventArgs();
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameFramework.WebRequest.WebRequestFailureEventArgs.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Create(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			object arg3 = ToLua.ToVarObject(L, 4);
			GameFramework.WebRequest.WebRequestFailureEventArgs o = GameFramework.WebRequest.WebRequestFailureEventArgs.Create(arg0, arg1, arg2, arg3);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			GameFramework.WebRequest.WebRequestFailureEventArgs obj = (GameFramework.WebRequest.WebRequestFailureEventArgs)ToLua.CheckObject(L, 1, typeof(GameFramework.WebRequest.WebRequestFailureEventArgs));
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SerialId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameFramework.WebRequest.WebRequestFailureEventArgs obj = (GameFramework.WebRequest.WebRequestFailureEventArgs)o;
			int ret = obj.SerialId;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SerialId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WebRequestUri(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameFramework.WebRequest.WebRequestFailureEventArgs obj = (GameFramework.WebRequest.WebRequestFailureEventArgs)o;
			string ret = obj.WebRequestUri;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index WebRequestUri on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ErrorMessage(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameFramework.WebRequest.WebRequestFailureEventArgs obj = (GameFramework.WebRequest.WebRequestFailureEventArgs)o;
			string ret = obj.ErrorMessage;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ErrorMessage on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UserData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameFramework.WebRequest.WebRequestFailureEventArgs obj = (GameFramework.WebRequest.WebRequestFailureEventArgs)o;
			object ret = obj.UserData;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index UserData on a nil value");
		}
	}
}

