//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityGameFramework_Runtime_ShutdownTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityGameFramework.Runtime.ShutdownType));
		L.RegVar("None", get_None, null);
		L.RegVar("Restart", get_Restart, null);
		L.RegVar("Quit", get_Quit, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityGameFramework.Runtime.ShutdownType>.Check = CheckType;
		StackTraits<UnityGameFramework.Runtime.ShutdownType>.Push = Push;
	}

	static void Push(IntPtr L, UnityGameFramework.Runtime.ShutdownType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityGameFramework.Runtime.ShutdownType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, UnityGameFramework.Runtime.ShutdownType.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Restart(IntPtr L)
	{
		ToLua.Push(L, UnityGameFramework.Runtime.ShutdownType.Restart);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Quit(IntPtr L)
	{
		ToLua.Push(L, UnityGameFramework.Runtime.ShutdownType.Quit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityGameFramework.Runtime.ShutdownType o = (UnityGameFramework.Runtime.ShutdownType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

