//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityGameFramework_Runtime_GameEntryWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("GameEntry");
		L.RegFunction("GetComponent", GetComponent);
		L.RegFunction("Shutdown", Shutdown);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<System.Type>(L, 1))
			{
				System.Type arg0 = (System.Type)ToLua.ToObject(L, 1);
				UnityGameFramework.Runtime.GameFrameworkComponent o = UnityGameFramework.Runtime.GameEntry.GetComponent(arg0);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<string>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				UnityGameFramework.Runtime.GameFrameworkComponent o = UnityGameFramework.Runtime.GameEntry.GetComponent(arg0);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityGameFramework.Runtime.GameEntry.GetComponent");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Shutdown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityGameFramework.Runtime.ShutdownType arg0 = (UnityGameFramework.Runtime.ShutdownType)ToLua.CheckObject(L, 1, typeof(UnityGameFramework.Runtime.ShutdownType));
			UnityGameFramework.Runtime.GameEntry.Shutdown(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

