//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_EventSystems_EventTrigger_TriggerEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.EventSystems.EventTrigger.TriggerEvent), typeof(UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData>));
		L.RegFunction("New", _CreateUnityEngine_EventSystems_EventTrigger_TriggerEvent);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_EventSystems_EventTrigger_TriggerEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.EventSystems.EventTrigger.TriggerEvent obj = new UnityEngine.EventSystems.EventTrigger.TriggerEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.EventSystems.EventTrigger.TriggerEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

